version: '3.8'
services:
  fastapi:
    build: .
    volumes:
      - ./app:/app
      - ./static:/static
    ports:
      - "8000:80"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
