version: '3.8'
services:
  fastapi:
    build: .
    volumes:
      - ./app:/app
      - ./static:/static
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  # mongodb_data:
